server:
  port: 8090
  
spring:
  application:
    name: Spring Boot Service
  boot:
    admin:
      client:
        enabled: true
        service-url: http://10.10.10.166:8080
  mvc:
    async:
      request-timeout: -1
      
info:
  version: "@project.version@"
  
logging:
  file: service.log